import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gettingStarted: [
    'getting-started/quickstart',
    'getting-started/installation',
    'getting-started/getting-started',
    'getting-started/docker',
    {
      type: 'category',
      label: 'Drive Cordum with MCP',
      items: [
        'mcp/tools',
        'mcp/resources',
        'mcp/prompts',
        'mcp/mutating-tools',
        'mcp/scope-preapproval',
        {
          type: 'category',
          label: 'MCP clients',
          items: [
            'mcp/quickstart-claude-code',
            'mcp/quickstart-cursor',
            'mcp/quickstart-vscode',
          ],
        },
      ],
    },
  ],
  concepts: [
    'concepts/architecture',
    'concepts/safety-kernel',
    'concepts/system-overview',
    'concepts/core',
    'concepts/output-policy',
    'concepts/output-safety',
    'concepts/packs',
    'concepts/workflow-step-types',
    'concepts/context-engine',
    'concepts/agent-protocol',
    'concepts/audit',
    'concepts/dashboard',
    'concepts/enterprise',
  ],
  tutorials: [
    {
      type: 'autogenerated',
      dirName: 'tutorials',
    },
  ],
  apiReference: [
    {
      type: 'autogenerated',
      dirName: 'api-reference',
    },
  ],
  operations: [
    {
      type: 'autogenerated',
      dirName: 'operations',
    },
  ],
};

export default sidebars;
