name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        We appreciate feature requests! Please provide details below.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: Is your feature request related to a problem? Describe the use case.
      placeholder: "I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe the solution you'd like
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Describe any alternative solutions you've considered

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this affect?
      options:
        - Safety Kernel
        - Workflow Engine
        - Job Scheduler
        - Pack System
        - API Server
        - Dashboard
        - Documentation
        - Other

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to contribute this feature
