export const API_PATHS = {
  stream: "/api/v1/stream",
  jobs: "/jobs",
  workflows: "/workflows",
  workflowRuns: "/workflows/runs",
  workers: "/workers",
  pools: "/pools",
  approvals: "/approvals",
  policy: "/policy",
  policyBundles: "/policy/bundles",
  policyRules: "/policy/rules",
  policySnapshots: "/policy/snapshots",
  policyAudit: "/policy/audit",
  config: "/config",
  schemas: "/schemas",
  packs: "/packs",
  artifacts: "/artifacts",
  locks: "/locks",
  memory: "/memory",
  traces: "/traces",
  dlq: "/dlq",
  auth: "/auth",
  edge: {
    sessions: "/edge/sessions",
    executions: "/edge/executions",
    approvals: "/edge/approvals",
    evaluate: "/edge/evaluate",
    events: "/edge/events",
    eventsBatch: "/edge/events/batch",
  },
} as const;
