{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cordum.serviceAccountName" . }}
  labels:
    {{- include "cordum.labels" . | nindent 4 }}
{{- end -}}
